# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : rouge
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

#source: source
#destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Stavros Kasidis
description: "Stavros personal blog"
keywords: "blog, developer, SEO, web, software, engineer"
url: http://www.stavroskasidis.com
baseurl: ""
# baseurl: ""

google_analytics: UA-98523909-1
#repo: http://github.com/AkiraGTX.github.io
disqus_shortname: "stavroskasidis"
disqus_site_shortname: "stavroskasidis"

# Author settings
author:
  name      : Stavros Kasidis
  job       : Software Engineer
  bio       : "Code enthusiast, fighting complexity and striving for quality."
  thumb     : /images/author.jpg
  email     : stavroskasidis@gmail.com
  url       : http://www.stavroskasidis.com
  github    : http://github.com/stavroskasidis
  #twitter   : http://twitter.com/nandomoreirame
  #facebook  : http://facebook.com/fernando.dev
  linkedin  : https://www.linkedin.com/in/stavros-kasidis-786b415a/

# navbar pages
navbar:
  # - slug: about
  #  title: About
  - slug: resume
    title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

# related posts inside a post?
related: true

timezone: Europe/Athens

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
